1.6.2
FalloutStudios/Axis pull request #78
Opened 2022-01-16 17:30 UTC by GhexterCortes

2022-01-16 17:36 UTC, GhexterCortes reviewed
dam

2022-01-17 07:08 UTC, GhexterCortes reviewed
:D

2022-01-17 13:43 UTC, BlobHuman requested changes

2022-01-17 13:43 UTC, BlobHuman commented on index.js
> +    // commands execution
```suggestion
    // Command execution
```

2022-01-17 13:43 UTC, BlobHuman commented on modules/axis.js
>          return SafeMessage.send(message.channel, { embeds: embeds });
idk but
```suggestion
        return SafeMessage.send(message.channel, { content: ' ', embeds: embeds });
```

2022-01-17 13:43 UTC, BlobHuman commented on modules/axis.js
>          return SafeInteract.editReply(interaction, { embeds: embeds });
```suggestion
        return SafeInteract.editReply(interaction, { content: ' ', embeds: embeds });
```

2022-01-17 13:43 UTC, BlobHuman commented on scripts/Utility.js
> +    }
Allow setting the commands and scripts optionally
```suggestion
    constructor(options = { logger: new Util.Logger('AxisUtility'), config: null, language: null, Client: null, scripts: [], commands: { MessageCommands: [], InteractionCommands: [] } }) {
        if(!options.config) throw new TypeError('No config provided');
        if(!options.language) throw new TypeError('No language provided');
        if(!options.Client) throw new TypeError('No client provided');

        this.logger = options.logger;
        this.config = options.config;
        this.language = options.language;
        this.scripts = options.scripts?.length ? options.scripts : [];
        this.commands = options.commands ? options.commands : { MessageCommands: [], InteractionCommands: [] };
        this.Client = options.Client;
    }
```

2022-01-17 13:56 UTC, merged